# @Author: westhide.yzw
# @Date: 2022-02-22 12:42:06
# @Last Modified by:   westhide.yzw
# @Last Modified time: 2022-02-22 12:42:06
# cargo +nightly fmt

# Misc
edition = "2021"

# Fundamental stuff
newline_style = "unix"

# comments
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true

# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"

# Ordering
reorder_impl_items = true
reorder_imports = true

# Options that can change the source code beyond whitespace/blocks
merge_derives = true

# Control options
# report_fixme="Unnumbered"
# report_todo="Unnumbered"
